<?php
session_start();

use Previewtechs\Cart\Cart;
use Previewtechs\Cart\CartItem;
use Previewtechs\Cart\Storage\Session;

class CartItemTests extends PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCartItemSetterGetter()
    {
        $cartItem = new CartItem();
        $cartItem->setName('product name');
        $this->assertTrue($cartItem->getName() == 'product name');
    }

    public function testAddToCart()
    {
        $item = new CartItem();
        $item->setName('Nokia');
        $item->setSku('BLACK');
        $item->setDescription('this is test description');
        $item->setNote('this is test note');
        $item->setPrice(100.00);

        $sessionStorage = new Session();
        $cart = new Cart('cart_name', $sessionStorage);
        $cart->addItem($item);
        var_dump($cart->getInfo());
    }
}