<?php

use Previewtechs\Cart\Cart;
use Previewtechs\Cart\CartItem;
use Previewtechs\Cart\Storage\SessionStorage;
//session_start();
class CartItemTests extends PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCartItemSetterGetter()
    {
        $cartItem = new CartItem();
        $cartItem->setName('product name');
        $this->assertTrue($cartItem->getName() == 'product name');
    }

    public function testAddToCart()
    {
        $cartItem = new CartItem();
        $cartItem->setName('Nokia');
        $cartItem->setSku('BLACK');
        $cartItem->setDescription('this is test description');
        $cartItem->setNote('this is test note');
        $cartItem->setPrice(45.55);

        $sessionStorage = new SessionStorage();
        $cart = new Cart('cart_name', $sessionStorage);
        $cart->addItem($cartItem);
        var_dump($cart->getItems());
    }
}